#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
LIBS_DIR="$SCRIPT_DIR/src"
if ! [[ -d "$LIBS_DIR" ]]; then
  LIBS_DIR="/usr/lib/wayweather"
fi
if ! [[ -d "$LIBS_DIR" ]]; then
  echo "[ERROR] Libraries are missing, cannot continue"
  echo "[INFO] Reinstall/Redownload wayweather"
  exit 1
fi

source "$LIBS_DIR/config.sh"
source "$LIBS_DIR/locations.sh"
source "$LIBS_DIR/output.sh"
source "$LIBS_DIR/meteo_api.sh"
source "$LIBS_DIR/version"

case $1 in
-h | --help)
  for i in "$@"; do
    case $i in
    -h | --help)
      if [[ "$@" == "--help --help" ]] || [[ "$@" == "--help -h" ]] || [[ "$@" == "-h --help" ]] || [[ "$@" == "-h -h" ]]; then
        show_help help
      fi
      ;;
    esac
  done
  show_help main
  ;;
-v | --version)
  for i in "$@"; do
    case $i in
    -h | --help)
      show_help version
      ;;
    esac
  done
  echo "wayweather $VERSION"
  ;;
-g | --get)
  for i in "$@"; do
    case $i in
    -h | --help)
      show_help get
      ;;
    --no-icon)
      NO_ICON=true
      ;;
    esac
  done
  waybar_return "$(if $NO_ICON; then echo "no-icon"; else echo ""; fi)"
  ;;
-s | --set)
  for i in "$@"; do
    case $i in
    -h | --help)
      show_help set
      ;;
    --lat=*)
      LAT="${i#*=}"
      ;;
    --long=*)
      LONG="${i#*=}"
      ;;
    --city=*)
      CITY="${i#*=}"
      ;;
    --country=*)
      COUNTRY="${i#*=}"
      ;;
    --units=*)
      UNITS="${i#*=}"
      ;;
    --save)
      SAVE=true
      ;;
    --skip-config)
      SKIP=true
      ;;
    esac
  done

  if [[ -v LAT ]] && [[ -v LONG ]] && [[ -v COUNTRY ]] && [[ -v CITY ]]; then
    if [[ "$LAT" != "" ]] && [[ "$LONG" != "" ]] && [[ "$COUNTRY" != "" ]] && [[ "$CITY" != "" ]]; then
      if $SAVE && [[ "$UNITS" != "" ]]; then
        write_loc "lat=$LAT" "long=$LONG" "country=$COUNTRY" "city=$CITY" "units=$UNITS" "$(if [[ -v SKIP ]]; then echo "skip"; else echo ""; fi)"
      fi
      write_conf set "lat=$LAT" "long=$LONG" "country=$COUNTRY" "city=$CITY" "$(if [[ "$UNITS" != "" ]]; then echo "units=$UNITS"; else echo ""; fi)"
    else
      echo "[ERROR] Arguments Empty"
      exit 1
    fi
  elif [[ -v UNITS ]]; then
    if [[ "$UNITS" != "" ]]; then
      write_conf set "units=$UNITS"
    else
      echo "[ERROR] Arguments Empty"
      exit 1
    fi
  else
    echo "[ERROR] Missing Arguments"
    exit 1
  fi
  ;;
-r | --reset)
  for i in "$@"; do
    case $i in
    -h | --help)
      show_help reset
      ;;
    -u | --units)
      UNITS=true
      ;;
    esac
  done
  if $UNITS; then
    make_conf
  else
    write_conf reset
  fi
  ;;
-l | --load)
  for i in "$@"; do
    case $i in
    -h | --help)
      show_help load
      ;;
    default)
      DEF="default"
      ;;
    *)
      if [[ "$i" =~ ^[0-9]+$ ]]; then
        ID="$i"
      fi
      ;;
    esac
  done
  load_loc "$DEF" "$ID"
  ;;
--list)
  for i in "$@"; do
    case $i in
    -h | --help)
      show_help list
      ;;
    esac
  done
  list_loc
  ;;
-p | --print)
  for i in "$@"; do
    case $i in
    -h | --help)
      show_help print
      ;;
    --no-icon)
      NO_ICON=true
      ;;
    esac
  done
  term_return "$(if $NO_ICON; then echo "no-icon"; else echo ""; fi)"
  ;;
-sd | --set-default)
  for i in "$@"; do
    case $i in
    -h | --help)
      show_help set-default
      ;;
    esac
  done
  default_loc
  ;;
-d | --delete)
  for i in "$@"; do
    case $i in
    -h | --help)
      show_help delete
      ;;
    -y | --yes)
      NOCONFIRM=true
      ;;
    *)
      if [[ "$i" =~ ^[0-9]+$ ]]; then
        DEL_NUM=true
        LOCATION_ID="$i"
      fi
      ;;
    esac
  done
  delete_loc "$(if [[ -v DEL_NUM ]]; then echo "$LOCATION_ID"; else echo ""; fi)" "$(if [[ -v NOCONFIRM ]]; then echo "yes"; else echo ""; fi)"
  ;;
-w | --daemon)
  for i in "$@"; do
    case $i in
    -h | --help)
      show_help set-daemon
      ;;
    --no-icon)
      NO_ICON=true
      ;;
    --location=*)
      LOCATION="${i#*=}"
      ;;
    --timer=*)
      TIMER="${i#*=}"
      ;;
    esac
  done
  daemon "$(if $NO_ICON; then echo "no-icon"; else echo ""; fi)" "$(if [[ -v LOCATION ]]; then echo "location=$LOCATION"; else echo ""; fi)" "$(if [[ -v TIMER ]]; then echo "timer=$TIMER"; else echo ""; fi)"
  ;;
*)
  echo -e "[ERROR] Invalid Input, Showing Help Message\n"
  show_help main
  ;;
esac
