#!/usr/bin/env bash

# Shell Script that houses the parser
# for OpenMeteoAPI

api_pull() {
  LAT="$1"
  LONG="$2"
  CITY="$3"
  COUNTRY="$4"
  UNITS="$5"

  case $UNITS in
  imp)
    TEMP_U="&temperature_unit=fahrenheit"
    WIND_U="&wind_speed_unit=mph"
    PREC_U="&precipitation_unit=inch"
    ;;
  met)
    TEMP_U=""
    WIND_U=""
    PREC_U=""
    ;;
  esac

  WTHR_API=$(curl -s "https://api.open-meteo.com/v1/forecast?latitude=$LAT&longitude=$LONG&current=temperature_2m,relative_humidity_2m,precipitation,cloud_cover,wind_speed_10m,wind_direction_10m,wind_gusts_10m,is_day,weather_code&timezone=auto$TEMP_U$WIND_U$PREC_U" | jq -c)

  TIME="$(echo "$WTHR_API" | jq -r '.current.time' | awk '{split($1, time, "T"); printf "%s %s",time[1],time[2]}')"
  TEMP="$(echo "$WTHR_API" | jq -r '.current.temperature_2m')$(echo "$WTHR_API" | jq -r '.current_units.temperature_2m')"
  HUMID="$(echo "$WTHR_API" | jq -r '.current.relative_humidity_2m')%"
  PREC="$(echo "$WTHR_API" | jq -r '.current.precipitation' | awk '{printf "%.2f",$1}') $(echo "$WTHR_API" | jq -r '.current_units.precipitation')"
  CLOUD="$(echo "$WTHR_API" | jq -r '.current.cloud_cover')%"
  WIND_S="$(echo "$WTHR_API" | jq -r '.current.wind_speed_10m') $(echo "$WTHR_API" | jq -r '.current_units.wind_speed_10m' | awk '{if ($1 == "mp/h") {print "mph"} else {print $1}}')"
  WIND_G="$(echo "$WTHR_API" | jq -r '.current.wind_gusts_10m') $(echo "$WTHR_API" | jq -r '.current_units.wind_gusts_10m' | awk '{if ($1 == "mp/h") {print "mph"} else {print $1}}')"

  WIND_ARR=(
    "North"
    "North East"
    "East"
    "South East"
    "South"
    "South West"
    "West"
    "North West"
  )
  WIND_DIR="$(echo "$WTHR_API" | jq -r '.current.wind_direction_10m')"
  WIND_DIR_LET="${WIND_ARR[$(echo "$WIND_DIR" | awk '{print int(($1 / 45) % 8 )}')]}"

  IS_DAY="$(echo "$WTHR_API" | jq -r '.current.is_day')"
  WC="$(echo "$WTHR_API" | jq -r '.current.weather_code')"

  declare -A WC_LIST

  WC_LIST=(
    ["0_0"]="󰖔 "
    ["0_1"]="󰖙 "
    ["1_0"]="󰖔 "
    ["1_1"]="󰖙 "
    ["2"]="󰖐 "
    ["3"]="󰖐 "
    ["45"]="󰖑 "
    ["48"]="󰖑 "
    ["51"]="󰖗 "
    ["53"]="󰖗 "
    ["55"]="󰖗 "
    ["56"]="󰙿 "
    ["57"]="󰙿 "
    ["61"]="󰖖 "
    ["63"]="󰖖 "
    ["65"]="󰖖 "
    ["66"]="󰙿 "
    ["67"]="󰙿 "
    ["71"]="󰖘 "
    ["73"]="󰖘 "
    ["75"]="󰼶 "
    ["77"]="󰖒 "
    ["80"]="󰖖 "
    ["81"]="󰖖 "
    ["82"]="󰖖 "
    ["85"]="󰼶 "
    ["86"]="󰼶 "
    ["95"]="󰖓 "
    ["96"]="󰖓 "
    ["99"]="󰖓 "
  )

  WI="${WC_LIST["$(echo "$WC $IS_DAY" | awk '{if ($1 <= 1) {printf "%s_%s",$1,$2} else {printf "%s",$1}}')"]}"

  declare -A WTHR

  WTHR=(
    ["CITY"]=$CITY
    ["COUNTRY"]=$COUNTRY
    ["TIME"]=$TIME
    ["TEMP"]=$TEMP
    ["HUMID"]=$HUMID
    ["PREC"]=$PREC
    ["CLOUD"]=$CLOUD
    ["WIND_S"]=$WIND_S
    ["WIND_G"]=$WIND_G
    ["WIND_DIR"]="$WIND_DIR_LET ($WIND_DIR°)"
    ["WI"]=$WI
  )

  printf "%s " "${WTHR[@]@K}"
}
